region = "ca-central-1"
private_key_file = "../certs/ovpn"
public_key_file = "../certs/ovpn.pub"
client_config_path = "../client_configs"
client_config_name = "aws-ovpn-client"
cert_details = "../cert_details"
